apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ctfd
  labels:
    io.kompose.service: nginx
spec:
  selector:
    matchLabels:
      io.kompose.service: nginx
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
      restartPolicy: Always